modality: wifi-csi

protocol: protocol3

data_unit: frame

random_split:
  ratio: 0.8
  random_seed: 0
  train_dataset:
    split: training
    scenes: None
    subjects: None
    actions: all
  val_dataset:
    split: validation
    scenes: None
    subjects: None
    actions: all

cross_scene_split:
  train_dataset:
    split: training
    scenes: [ E01, E02, E03 ]
    subjects: None
    actions: all
  val_dataset:
    split: validation
    scenes: [ E04 ]
    subjects: None
    actions: all

cross_subject_split:
  train_dataset:
    split: training
    scenes: None
    subjects: [ S01, S02, S03, S04, S06, S07, S08, S09 ]
    actions: all
  val_dataset:
    split: validation
    scenes: None
    subjects: [ S05, S10 ]
    actions: all

manual_split:
  train_dataset:
    split: training
    scenes: None
    subjects: [S01]
    actions: [A01]
  val_dataset:
    split: validation
    scenes: None
    subjects: [S05]
    actions: [A22]

split_to_use: manual_split

device: gpu
weight_path: None
epochs: 2
init_rand_seed: 0
train_loader:
  batch_size: 2
validation_loader:
  batch_size: 1

output_folder: ./ckpt/
