modality: mmwave

protocol: protocol3

data_unit: frame

random_split:
  ratio: 0.8
  random_seed: 0
  train_dataset:
    split: training
    scenes: None
    subjects: None
    actions: all
  val_dataset:
    split: validation
    scenes: None
    subjects: None
    actions: all

cross_scene_split:
  train_dataset:
    split: training
    scenes: [ E01, E02, E03 ]
    subjects: None
    actions: all
  val_dataset:
    split: validation
    scenes: [ E04 ]
    subjects: None
    actions: all

cross_subject_split:
  train_dataset:
    split: training
    scenes: None
    subjects: [ S01, S02, S03, S04, S06, S07, S08, S09 ]
    actions: all
  val_dataset:
    split: validation
    scenes: None
    subjects: [ S05, S10 ]
    actions: all

manual_split:
  train_dataset:
    split: training
    scenes: None
    subjects: [S01]
    actions: [A01]
  val_dataset:
    split: validation
    scenes: None
    subjects: [S31, S32, S33, S34, S35]
    actions: [A01, A02, A03, A04, A06, A07, A08, A09, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21, A22, A23, A24, A25, A26, A27]

split_to_use: manual_split

device: gpu
weight_path: None
epochs: 100
init_rand_seed: 0
train_loader:
  batch_size: 2
validation_loader:
  batch_size: 1

output_folder: ./ckpt/
